openapi: 3.0.3
info:
  title: Management APP - API
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: UserManagement
    description: Operations related to users management
paths:
  /users/:
    $ref: './users/users.yml'
  /users/signUp:
    $ref: './users/users_signUp.yml'
  /users/login:
    $ref: './users/users_login.yml'
  /users/loginFromServiceToken:
    $ref: './users/users_loginFromServiceToken.yml'
  /users/{id}:
    $ref: './users/users_$id$.yml'
  /users/{id}/changePassword:
    $ref: './users/users_$id$_changePassword.yml'
  /users/{id}/updateRole:
    $ref: './users/users_$id$_updateRole.yml'

  /quadrants:
    $ref: './quadrants/quadrants.yml'
  /quadrants/active:
    $ref: './quadrants/quadrants_active.yml'
  /quadrants/{id}:
    $ref: './quadrants/quadrants_$id$.yml'
  /quadrants/{id}/linkFire:
    $ref: './quadrants/quadrants_$id$_linkFire.yml'

  /fires:
    $ref: './fires/fires.yml'
  /fires/{id}:
    $ref: './fires/fires_$id$.yml'
  /fires/{id}/extinguishQuadrant:
    $ref: './fires/fires_$id$_extinguishQuadrant.yml'
  /fires/{id}/extinguishFire:
    $ref: './fires/fires_$id$_extinguishFire.yml'

  /organizations:
    $ref: './organizations/organizations.yml'
  /organizations/{id}:
    $ref: './organizations/organizations_$id$.yml'

