openapi: 3.0.3
info:
  title: Management APP - API
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: UserManagement
    description: Operations related to users management
paths:
  /users/:
    $ref: './users/users.yml'
  /users/signUp:
    $ref: './users/users_signUp.yml'
  /users/login:
    $ref: './users/users_login.yml'
  /users/loginFromServiceToken:
    $ref: './users/users_loginFromServiceToken.yml'
  /users/{id}:
    $ref: './users/users_$id$.yml'
  /users/{id}/changePassword:
    $ref: './users/users_$id$_changePassword.yml'
  /users/{id}/updateRole:
    $ref: './users/users_$id$_updateRole.yml'

  /quadrants:
    $ref: './quadrants/quadrants.yml'

